name: trustbite_mobile
description: TrustBite mobile application built with Flutter and Dart.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_auth_cognito: ^2.12.0
  amplify_flutter: ^2.12.0
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.3
  image_picker: ^1.2.3
  maplibre_gl: ^0.26.2
  permission_handler: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#120906"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/app_icon_foreground.png
    - assets/icons/
    - assets/bg/
