variable "create_live_resources" {
  description = "Guardrail flag for future live resources."
  type        = bool
}

variable "environment" {
  description = "Environment name."
  type        = string
}

variable "name_prefix" {
  description = "Non-secret resource name prefix."
  type        = string
}

variable "rds_master_user_secret_arn" {
  description = "Secrets Manager ARN generated by RDS managed master password."
  type        = string
  default     = null
}

variable "receipt_bucket_arn" {
  description = "S3 receipt bucket ARN for task-role policy scoping."
  type        = string
  default     = null
}

variable "receipt_object_prefix" {
  description = "S3 object prefix used for receipt uploads."
  type        = string
}

variable "redis_auth_token_secret_arn" {
  description = "Optional Secrets Manager ARN containing REDIS_PASSWORD."
  type        = string
  default     = null
}

variable "task_secret_policy_enabled" {
  description = "Known-at-plan-time gate for ECS execution/task secret-read policy creation."
  type        = bool
  default     = false
}

variable "tags" {
  description = "Common non-secret tags."
  type        = map(string)
}
